source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GooglePlacesSearchController_Example', :exclusive => true do
  pod "GooglePlacesSearchController", :path => "../"
end

target 'GooglePlacesSearchController_Tests', :exclusive => true do
  pod "GooglePlacesSearchController", :path => "../"

  
end
